### ISSUE TITLE
Dictionary doesn't load

### ISSUE THREAD

**Issue by webaround** [ethereum/ens-registrar-dapp#187]
It happens from time to time for me that the dictionary doesn't load when I enter a name on which I would like to bid. When I go back to the main page, click on one of the names which are currently open, and enter my name again, the dictionary loads (with a short delay). This seems to be a bit random to me, but at the moment it is the only way via which the dictionary finally loads. As I'm not a programmer, I can't tell which of the information given in the console would be helpful to identify the issue. Just wanted to let you know that this happened quite often over the last weeks. I use MetaMask in Chrome.

**Comment by rsimonton** [comment]
+1

**Comment by Ethqone** [comment]
+1

**Comment by markshep** [comment]
I'm having worse problems than the original reporter.  I'm trying to open auctions on a few domains, but I can't because most of the time the dictionary doesn't load at all.  I have occasionally seen it load, but that's only about 1% of the time and I think after waiting ages :-(.  This is a real problem that's preventing me from using the system.  I'm using Metamask on Chrome on macOS.

**Comment by markshep** [comment]
My initial thought was that the dictionary was being loaded off the blockchain and my connection to peers on the network was slow/bad, but after downloading the source code and poking around it turns out it's baked into the JavaScript, so it should load very quickly for me as I've got a fast internet connection.

Looking at the console I did see an exception which kept getting fired and which seemed unrelated, but as the cause was fairly simple to track down I fixed it.  That actually turned out to fix this problem and the fix has now been merged into the master branch (see GH-196).

I think what was happening was that the exception was firing and preventing the code that detected the dictionary had finished loading from being reached, so the internal state of the dapp was incorrect.  The reason why I'd been seeing it more that other commentators here is simply that more time had elapsed.

The actual bug I fixed was in picking a random name, which was done from a portion of the dictionary relative to how much of the eight week launch period had elapsed.  But it was uncapped, so beyond the initial eight weeks it was more and more likely to try and access beyond the end of the dictionary, thus causing the exception.

Anyway, once the static files have been rebuilt from the source code and they've been published to https://registrar.ens.domains/ this problem should no longer happen.

**Comment by markshep** [comment]
Looks like the static page generation and publish has now happened, so I think this issue can be closed now.  @webaround - please can you check to see if it works for you now?

**Comment by Ethqone** [comment]
@markshep Working like a charm for me now! Thanks for the help on this!

**Comment by webaround** [comment]
Works - very fast and stable now! Thank you very much, @markshep :-)

**Comment by webaround** [comment]
closing this now.
