### ISSUE TITLE
Errors on bid page

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/ens-registrar-dapp#80]
I'm getting JavaScript errors when bidding on https://registrar.ens.domains/#exxtrafamous

"Exception from Tracker afterFlush function:"
"ReferenceError: BigNumber is not defined"
"Dummy hashes not working"

![screen shot 2017-05-04 at 14 23 06](https://cloud.githubusercontent.com/assets/731743/25705494/678459bc-30d5-11e7-99db-46e497d97307.png)

**Comment by shonjs** [comment]
same issue here

**Comment by rboe** [comment]
Same here too.
Windows / Chrome / Metamask

MetaMask - injected web3
SourceSansPro-Semibold.otf Failed to load resource: the server responded with a status of 404 ()
SourceSansPro-Regular.otf Failed to load resource: the server responded with a status of 404 ()
SourceSansPro-Bold.otf Failed to load resource: the server responded with a status of 404 ()
SourceSansPro-ExtraLight.otf Failed to load resource: the server responded with a status of 404 ()
a6c126a….js:formatted:84984 checkNetwork ...
/sockjs/info?cb=voxb4rdi9w Failed to load resource: the server responded with a status of 404 ()
a6c126a….js:formatted:85016 done initialiting null 0x6090a6e47849629b7245dfa1ca21d94cd15878ef
a6c126a….js:formatted:85147 update Reveal Names:  
a6c126a….js:formatted:82544 network?! main
a6c126a….js:formatted:82934 launchRatio 0.024599067460321797
a6c126a….js:formatted:82987 name: encryption
**a6c126a….js:formatted:1263 Exception from Tracker afterFlush function:
a6c126a….js:formatted:1263 ReferenceError: BigNumber is not defined
    at h.TemplateInstance.r.randomHash (a6c126a….js:formatted:82946)
    at h.TemplateInstance.r.createHashesArray (a6c126a….js:formatted:82970)
    at h.TemplateInstance.<anonymous> (a6c126a….js:formatted:82988)
    at a6c126a….js:formatted:52330
    at Function.e._withTemplateInstanceFunc (a6c126a….js:formatted:52460)
    at n (a6c126a….js:formatted:52326)
    at h.View.<anonymous> (a6c126a….js:formatted:52361)
    at a6c126a….js:formatted:51540
    at Object.h._withCurrentView (a6c126a….js:formatted:51758)
    at a6c126a….js:formatted:51539**
/preimages.js:1146803 Names loaded
a6c126a….js:formatted:85186 1146799 known names loaded. Now checking for events since block 3655364

**Comment by Arachnid** [comment]
This should be fixed now; please reopen if it's still not working for you.
